package LeetCode;

public class P_389_findTheDifference {
    /*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

     */
    public static char findTheDifference(String s, String t) {
        // Gulnara      ab   97+98 = 195
        // NaraGuml     ac d  97+98+100=295
        // 295-195=100 (d)
        int sumS = 0;
        int sumT = 0;
        for(char c : s.toCharArray()){
            sumS += c;
        }
//        for(int i = 0; i<s.length();i++){
//            sumS = sumS + i;
//        }
        for(char c : t.toCharArray()){
            sumT += c;
        }
        return (char)(sumT-sumS);
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("abc", "adbc"));
    }
}
